### ISSUE TITLE
problem with installation on ubuntu 16.10

### ISSUE THREAD

**Issue by karozas** [snhirsch/mustang-midi-bridge#3]
hi, Ι m having issueswith installation on ubuntu 16.10. I get this :   sakis@sakis-All-Series:~/mustang-midi-bridge$ make CPPFLAGS=-DRTMIDI_2_0
g++ -O3 -DNDEBUG -DRTMIDI_2_0  -c -o mustang_midi.o mustang_midi.cpp
mustang_midi.cpp:4:20: fatal error: RtMidi.h: No such file or directory
 #include <RtMidi.h>
                    ^
compilation terminated.
<builtin>: recipe for target 'mustang_midi.o' failed
make: *** [mustang_midi.o] Error 1
sakis@sakis-All-Series:~/mustang-midi-bridge$ make
g++ -O3 -DNDEBUG -MP -MMD   -c -o mustang_midi.o mustang_midi.cpp
mustang_midi.cpp:4:20: fatal error: RtMidi.h: No such file or directory
 #include <RtMidi.h>
                    ^
compilation terminated.
<builtin>: recipe for target 'mustang_midi.o' failed
make: *** [mustang_midi.o] Error 1

sakis@sakis-All-Series:~$ dpkg -l | grep libusb
ii  libgusb2:amd64                                  0.2.9-1                                     amd64        GLib wrapper around libusb1
ii  libusb-1.0-0:amd64                              2:1.0.20-1                                  amd64        userspace USB programming library
ii  libusb-1.0-0-dev:amd64                          2:1.0.20-1                                  amd64        userspace USB programming library development files
ii  libusb-1.0-doc                                  2:1.0.20-1                                  all          documentation for userspace USB programming
ii  libusbmuxd4:amd64                               1.0.10-3                                    amd64        USB multiplexor daemon for iPhone and iPod Touch devices - library

**Comment by snhirsch** [comment]
That error suggests you are missing the librtmidi-dev package.  Make sure you have both the 'librtmidi1' and 'librtmidi-dev' packages installed (headers are in the latter).  If not sure, please post the results of this command:

`$ dpkg -l | grep -i midi`

**Comment by karozas** [comment]
I ve got this   i  freepats                                        20060219-1                                  all          Free patch set for MIDI audio synthesis
ii  libfluidsynth1:amd64                            1.1.6-3build1                               amd64        Real-time MIDI software synthesizer (runtime library)
ii  librtmidi-dev:amd64                             2.1.1~ds0-4                                 amd64        C++ library for realtime MIDI input/ouput (development files)
ii  librtmidi3:amd64                                2.1.1~ds0-4                                 amd64        C++ library for realtime MIDI input/ouput
ii  libwildmidi-config                              0.4.0-1                                     all          software MIDI player configuration
ii  libwildmidi2:amd64                              0.4.0-1                                     amd64        software MIDI player library

**Comment by karozas** [comment]
sakis@sakis-All-Series:~$ dpkg -l | grep -i midi
ii  freepats                                        20060219-1                                  all          Free patch set for MIDI audio synthesis
ii  libfluidsynth1:amd64                            1.1.6-3build1                               amd64        Real-time MIDI software synthesizer (runtime library)
ii  librtmidi-dev:amd64                             2.1.1~ds0-4                                 amd64        C++ library for realtime MIDI input/ouput (development files)
ii  librtmidi3:amd64                                2.1.1~ds0-4                                 amd64        C++ library for realtime MIDI input/ouput
ii  libwildmidi-config                              0.4.0-1                                     all          software MIDI player configuration
ii  libwildmidi2:amd64                              0.4.0-1                                     amd64        software MIDI player library

**Comment by snhirsch** [comment]
As I mentioned above, you are missing the librtmidi-dev package.

**Comment by karozas** [comment]
excuse my ignorance but how do I solve this?

**Comment by karozas** [comment]
ok solved it thanks

**Comment by snhirsch** [comment]
At first I didn't see the librtmidi-dev package, but then noticed that it was there in your list.  That's why I removed my reply.  What did you do to solve the problem?  Would appreciate your posting it in order to help others.  Thanks - and please let me know if you have any more problems.

**Comment by karozas** [comment]
in the file mustang_midi.cpp I changed this : #include <RtMidi.h> with this:  #include </usr/include/Rtmidi/RtMidi.h> and then ...sudo make ....worked

**Comment by karozas** [comment]
tomorrow I will test it with my Mustang I and I will notify you for any problems.thank you for this project.its amazing.

**Comment by snhirsch** [comment]
Interesting.  It appears that the newer Ubuntu package puts the headers in a subdirectory.  BTW, /usr/include is always on the compiler's path, so you could simply do:
`#include <RtMidi/RtMidi.h>`
Thanks for the report.  I'll update the build process to work with both cases.
I have only a Mustang III and IIIv2 here so the Mustang I has not been tested (I based the code on reports from other users.)

**Comment by karozas** [comment]
now I m getting this : Dec  1 18:19:54 sakis-All-Series systemd-udevd[3696]: Process '/bin/bash -c '/bin/echo /usr/local/bin/mustang_bridge_start | /usr/bin/at now'' failed with exit code 1.

**Comment by karozas** [comment]
sudo tail -f /var/log/syslog
Dec  1 18:22:16 sakis-All-Series anacron[710]: Job `cron.daily' terminated
Dec  1 18:22:16 sakis-All-Series anacron[710]: Normal exit (1 job run)
Dec  1 18:22:48 sakis-All-Series kernel: [  357.522965] usb 4-4: USB disconnect, device number 4
Dec  1 18:22:48 sakis-All-Series systemd-udevd[3945]: Process '/usr/local/bin/mustang_bridge_stop' failed with exit code 1.
Dec  1 18:22:51 sakis-All-Series kernel: [  360.818424] usb 4-4: new full-speed USB device number 5 using ohci-pci
Dec  1 18:22:51 sakis-All-Series kernel: [  361.034779] usb 4-4: New USB device found, idVendor=1ed8, idProduct=0004
Dec  1 18:22:51 sakis-All-Series kernel: [  361.034788] usb 4-4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Dec  1 18:22:51 sakis-All-Series kernel: [  361.034793] usb 4-4: Product: Mustang Amplifier
Dec  1 18:22:51 sakis-All-Series kernel: [  361.034798] usb 4-4: Manufacturer: FMIC
Dec  1 18:22:51 sakis-All-Series kernel: [  361.034802] usb 4-4: SerialNumber: BAD5FF393232553057106725
Dec  1 18:22:51 sakis-All-Series kernel: [  361.046158] hid-generic 0003:1ED8:0004.0005: hiddev0,hidraw1: USB HID v1.10 Device [FMIC Mustang Amplifier] on usb-0000:00:13.0-4/input0
Dec  1 18:22:51 sakis-All-Series mtp-probe: checking bus 4, device 5: "/sys/devices/pci0000:00/0000:00:13.0/usb4/4-4"
Dec  1 18:22:51 sakis-All-Series mtp-probe: bus: 4, device: 5 was not an MTP device
Dec  1 18:22:51 sakis-All-Series gnome-software[2239]: failed to load stock icon input-keyboard: Το εικονίδιο 'input-keyboard' δεν περιέχεται στο θέμα (null)
Dec  1 18:22:51 sakis-All-Series systemd-udevd[3957]: Process '/bin/bash -c '/bin/echo /usr/local/bin/mustang_bridge_start | /usr/bin/at now'' failed with exit code 1.
Dec  1 18:22:51 sakis-All-Series rtkit-daemon[2179]: Supervising 4 threads of 1 processes of 1 users.
Dec  1 18:22:51 sakis-All-Series rtkit-daemon[2179]: Successfully made thread 3973 of process 2178 (n/a) owned by '1000' RT at priority 5.
Dec  1 18:22:51 sakis-All-Series rtkit-daemon[2179]: Supervising 5 threads of 1 processes of 1 users.
Dec  1 18:22:52 sakis-All-Series colord-sane: io/hpmud/pp.c 627: unable to read device-id ret=-1

**Comment by karozas** [comment]
Dec  1 18:39:58 sakis-All-Series kernel: [ 1387.578535] usb 7-1: new full-speed USB device number 5 using xhci_hcd
Dec  1 18:39:58 sakis-All-Series kernel: [ 1387.889706] usb 7-1: New USB device found, idVendor=2573, idProduct=10c2
Dec  1 18:39:58 sakis-All-Series kernel: [ 1387.889715] usb 7-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Dec  1 18:39:58 sakis-All-Series kernel: [ 1387.889720] usb 7-1: Product: MIDIMATE II
Dec  1 18:39:58 sakis-All-Series kernel: [ 1387.889725] usb 7-1: Manufacturer: ESI Audiotechnik GmbH
Dec  1 18:39:58 sakis-All-Series kernel: [ 1387.889729] usb 7-1: SerialNumber: 1.0.0
Dec  1 18:39:58 sakis-All-Series mtp-probe: checking bus 7, device 5: "/sys/devices/pci0000:00/0000:00:02.5/0000:02:00.0/usb7/7-1"
Dec  1 18:39:58 sakis-All-Series mtp-probe: bus: 7, device: 5 was not an MTP device
Dec  1 18:39:58 sakis-All-Series pulseaudio[2178]: [pulseaudio] module-alsa-card.c: Failed to find a working profile.
Dec  1 18:39:58 sakis-All-Series pulseaudio[2178]: [pulseaudio] module.c: Failed to load module "module-alsa-card" (argument: "device_id="1" name="usb-ESI_Audiotechnik_GmbH_MIDIMATE_II_1.0.0-00" card_name="alsa_card.usb-ESI_Audiotechnik_GmbH_MIDIMATE_II_1.0.0-00" namereg_fail=false tsched=yes fixed_latency_range=no ignore_dB=no deferred_volume=yes use_ucm=yes card_properties="module-udev-detect.discovered=1""): initialization failed.
Dec  1 18:40:02 sakis-All-Series gnome-software[2239]: failed to load stock icon input-keyboard: Το εικονίδιο 'input-keyboard' δεν περιέχεται στο θέμα (null)
Dec  1 18:40:02 sakis-All-Series colord-sane: io/hpmud/pp.c 627: unable to read device-id ret=-1

**Comment by karozas** [comment]
this is 60-midi rules file:                                                                                                                                # Must customize vendor and product id for your controller
ACTION=="add|change", SUBSYSTEM=="usb", ATTRS{idVendor}=="2753", ATTRS{idProduct}=="10c2", RUN+="/bin/bash -c '/bin/echo /usr/local/bin/mustang_bridge_start | /usr/bin/at now'"
ACTION=="remove", ENV{ID_VENDOR_ID}=="2753", ENV{ID_MODEL_ID}=="10c2", ENV{DEVTYPE}=="usb_device", RUN+="/usr/local/bin/mustang_bridge_stop"

**Comment by karozas** [comment]
this is mustang_bridge_start file :                                                                                                     #!/usr/bin/python

import os
from os.path import expanduser
from pwd import getpwnam
from grp import getgrnam

import glob
import syslog
from string import split

import usb.core

rundir = "/var/run/mustang/"

# Mustang USB parms
mustang_vid = 0x1ed8
mustang_pids = ( 0x0004, 0x0005, 0x000a, 0x0010, 0x0012, 0x0014, 0x0016 )

####### Start User Edits #########

# Controller USB parms
control_vid = 0x2753
control_pid = 0x10c2

# Controller MIDI device
midi_device = 1

# MIDI listen channel
midi_channel = 1

######## End User Edits ##########

# Look for devices
controller = usb.core.find( idVendor = control_vid, idProduct = control_pid )
if ( not controller ):
    sys.exit( 0 )

mustang = False
for pid in mustang_pids:
    device = usb.core.find( idVendor = mustang_vid, idProduct = pid )
    if ( device ):
        mustang = True
        break

if ( not mustang ):
    sys.exit( 0 )

pid = os.getpid()
# syslog.syslog( "%d: Starting" % pid )

# Look for atomic pid file
os.chdir( rundir )
filelist = glob.glob( 'mustang_*' )
if len( filelist ) != 1:
    syslog.syslog( "%d: /var/run/mustang is not properly setup" % pid )
    sys.exit( 0 )

# Found file.  Parse out the PID of the process that created it.
lockfile = filelist[0]
oldpid = split( lockfile, '_' )[1]

# syslog.syslog( "%d: Check for path /proc/%s" % (pid, oldpid) )
if not os.path.exists( "/proc/%s" % oldpid ):
    # No such process, ok to start ours
    # syslog.syslog( "%d: Renaming %s to mustang_%d" % (pid, lockfile, pid) )
    try:
        os.rename( lockfile, "mustang_%d" % os.getpid() ) 
    except Exception, e:
        pass
        # syslog.syslog( "%d: Unable to rename file" % pid )
    else:
        # syslog.syslog( "%d: About to exec" % pid )
        # Drop privileges and start the program
        pwObj = getpwnam('mustang-user')
        os.setgid( pwObj.pw_gid )
        
        # Need secondary groups to access MIDI and USB devices
        sec_gids = ( getgrnam('plugdev').gr_gid, getgrnam('audio').gr_gid )
        os.setgroups( sec_gids )
        
        os.setuid( pwObj.pw_uid )
        os.execl( "/usr/local/bin/mustang_midi", "mustang_midi", "%s" % midi_device, "%s" % midi_channel )

**Comment by snhirsch** [comment]
Let's cover the basics first.  Do you have 'bash' and 'at' installed on the computer?  Check this by doing:
`type at`
`type bash`

Also verify that `/bin/echo` and `/usr/local/bin/mustang_bridge_start` exist.

Just noticed:  You have a couple of typos.  The interface is reported as:
`
Dec 1 18:39:58 sakis-All-Series kernel: [ 1387.889706] usb 7-1: New USB device found, idVendor=2573, idProduct=10c2
`
but you have put '2753' in both the udev rule and the startup python file.

**Comment by snhirsch** [comment]
Hi, just wondering if you are up and running?  Let me know if there's anything further I can do to help.

**Comment by karozas** [comment]
hi I was and I will be too busy this days.I let you know if Ihave something new tnx for your concerne


________________________________
Από: snhirsch <notifications@github.com>
Στάλθηκε: Κυριακή, 4 Δεκεμβρίου 2016 9:58 μμ
Προς: snhirsch/mustang-midi-bridge
Κοιν.: karozas; State change
Θέμα: Re: [snhirsch/mustang-midi-bridge] problem with installation on ubuntu 16.10 (#3)


Hi, just wondering if you are up and running? Let me know if there's anything further I can do to help.

-

**Comment by snhirsch** [comment]
I cannot tell from your reply whether or not you have solved your problem.  Would very much appreciate your being clear one way or the other so know if the issue should stay open.

**Comment by karozas** [comment]
no I havent solved it cause I didnt  had the time.I believe at the end of the week I will get back to the issue



________________________________
Από: snhirsch <notifications@github.com>
Στάλθηκε: Δευτέρα, 5 Δεκεμβρίου 2016 4:13 πμ
Προς: snhirsch/mustang-midi-bridge
Κοιν.: karozas; State change
Θέμα: Re: [snhirsch/mustang-midi-bridge] problem with installation on ubuntu 16.10 (#3)


I cannot tell from your reply whether or not you have solved your problem. Would very much appreciate your being clear one way or the other so know if the issue should stay open.

-

**Comment by karozas** [comment]
Well, this what I m getting so far
:sakis@sakis-All-Series:~$ type at
at is /usr/bin/at
sakis@sakis-All-Series:~$ type bash
bash is /bin/bash
sakis@sakis-All-Series:~$

**Comment by karozas** [comment]
https://cloud.githubusercontent.com/assets/23744834/20924895/6357684a-bbbc-11e6-8d55-794912da552a.png

**Comment by karozas** [comment]
https://cloud.githubusercontent.com/assets/23744834/20924955/ad75b972-bbbc-11e6-96d3-6439cfacb395.png

**Comment by snhirsch** [comment]
Have you fixed the typo I pointed out above?

**Comment by karozas** [comment]
as for the idvendor and idProduct of midi device I placed them  as you suggest in the instructions in the 60-midi.rules like this :

````
# Must customize vendor and product id for your controller
ACTION=="add|change", SUBSYSTEM=="usb", ATTRS{idVendor}=="2753", ATTRS{idProduct}=="10c2", RUN+="/bin/bash -c '/bin/echo /usr/local/bin/mustang_bridge_start | /usr/bin/at now'"
ACTION=="remove", ENV{ID_VENDOR_ID}=="2753", ENV{ID_MODEL_ID}=="10c2", ENV{DEVTYPE}=="usb_device", `RUN+="/usr/local/bin/mustang_bridge_stop`
````


and to mustang_midi_start file like this :


````
#` Controller USB parms
control_vid = 0x2753
control_pid = 0x10c2

# Controller MIDI device
midi_device = 2

# MIDI listen channel
midi_channel = 1``
```

**Comment by karozas** [comment]
What should I do now?

**Comment by karozas** [comment]
the midi_device=2 is because I get this:
```
sakis@sakis-All-Series:~$ amidi -l
Dir Device    Name
IO  hw:2,0,0  MIDIMATE II MIDI 1
IO  hw:2,0,1  MIDIMATE II MIDI 2

```

**Comment by karozas** [comment]
is there a way of forcing mustang  midi bridge to start ?

**Comment by snhirsch** [comment]
I'm not sure if we're running into a language problem or not, but you are using the incorrect id!  This is what you posted the system log:

`Dec 1 18:39:58 sakis-All-Series kernel: [ 1387.889706] usb 7-1: New USB device found, idVendor=2573, idProduct=10c2`

Please note that is 2573.  You have used the wrong number: "2753" when editing the Mustang files.

**Comment by karozas** [comment]
Oh man what I was thinking?You were  definitely right.I ve got it working on my rasberry pi3 running Rasbian Jessie.Everything works(program changes and cc) but if I leave it alone for 1 minute or so it stops responding for a while but afterwards it returns to normal behaviour.Thank you very much for your patience.On ubuntu I will check tommorow.

**Comment by karozas** [comment]
on ubuntu I will check tommorow

**Comment by snhirsch** [comment]
I had some USB misbehavior with RPi, so perhaps that's what you're experiencing.  The Beaglebone works much more reliably for only a little more money.  But, anyway, glad that you are running!
