### ISSUE TITLE
Raspbian (Debian) Stretch?

### ISSUE THREAD

**Issue by jkuzma** [snhirsch/mustang-midi-bridge#4]
From the install instructions...
Can't seem to get the librtmidi-dev package to install properly on Debian Stretch.
This is on a RPi3-B.
Looks like librtmidi3 is reported back from "dpkg --get-selections".
Is this a case where there is a lib but no header file since I can't pull the "dev" package?
In a nutshell...there is no "RtMidi.h" on my system. That breaks the makefile.

**Comment by snhirsch** [comment]
I think this is a question better addressed to the Stretch maintainers.  In a pinch, perhaps you can install rtmidi from the upstream sources?

**Comment by kurtjensen** [comment]
I had this happen to me also on Stretch with an RPI3B+.

I saw that the RtMidi.h was available, so I added it's path into the makefile by adding a line:
INC = -I/usr/include/rtmidi
near the top of the file, and then passing that to g++ by adding to the compiler options line like this:
opt: CXXFLAGS += -O3 -DNDEBUG $(INC)

I suppose I should do it to the debug: line in the makefile too, but I do not plan to be building a debug version for now.

**Comment by snhirsch** [comment]
Thanks for the feedback. Looks like newer rtmidi packages moved the header to a subdirectory.  I'll add that to the Makefile (won't hurt if the directory is not there, i.e. older systems).

**Comment by snhirsch** [comment]
Would you please put this at the top of an unmodified Makefile and let me know if it solves the build problem?

RTMIDI_INC := $(shell ls -d /usr/include/rtmidi 2>/dev/null | tail -n 1)

ifneq (,$(RTMIDI_INC))
  INCDIRS += -I/usr/include/rtmidi
endif

**Comment by kurtjensen** [comment]
```
RTMIDI_INC := $(shell ls -d /usr/include/rtmidi 2>/dev/null | tail -n 1)

ifneq (,$(RTMIDI_INC))
INCDIRS += -I/usr/include/rtmidi
endif
```

Those additions to the Makefile allowed me an error-free build.  Thanks!
Also, thanks for doing this project and posting it!   I look forward to getting my FCB1010 to control my mustang!  Cheers!

**Comment by snhirsch** [comment]
Thanks for testing that out.  I just committed the fix.
